[2022-04-25 06:56:58,084] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_pq_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-25 06:56:58,128] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_pq_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-25 06:56:58,130] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 06:56:58,131] {taskinstance.py:1250} INFO - Starting attempt 4 of 4
[2022-04-25 06:56:58,132] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 06:56:58,180] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): format_xl_to_pq_task> on 1997-01-01 00:00:00+00:00
[2022-04-25 06:56:58,190] {standard_task_runner.py:52} INFO - Started process 483 to run task
[2022-04-25 06:56:58,198] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_pq_task', 'scheduled__1997-01-01T00:00:00+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmptqbzt3p0', '--error-file', '/tmp/tmp_30bqrt_']
[2022-04-25 06:56:58,201] {standard_task_runner.py:80} INFO - Job 318: Subtask format_xl_to_pq_task
[2022-04-25 06:56:58,627] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_pq_task scheduled__1997-01-01T00:00:00+00:00 [running]> on host 64c7187bd08f
[2022-04-25 06:56:58,901] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 06:56:59,084] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_pq_task
AIRFLOW_CTX_EXECUTION_DATE=1997-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1997-01-01T00:00:00+00:00
[2022-04-25 06:56:59,091] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_to_gcs_dag.py", line 36, in format_xl_to_pq
    df = pd.DataFrame(pd.read_excel(src_file))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1192, in __init__
    content_or_path=path_or_buffer, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1071, in inspect_excel_format
    content_or_path, "rb", storage_options=storage_options, is_text=False
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow//laucnty97.xlsx'
[2022-04-25 06:56:59,211] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_pq_task, execution_date=19970101T000000, start_date=20220425T065658, end_date=20220425T065659
[2022-04-25 06:56:59,270] {standard_task_runner.py:98} ERROR - Failed to execute job 318 for task format_xl_to_pq_task ([Errno 2] No such file or directory: '/opt/airflow//laucnty97.xlsx'; 483)
[2022-04-25 06:56:59,302] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 06:56:59,575] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
