[2022-04-25 07:14:24,855] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_pq_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-25 07:14:24,893] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_pq_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-25 07:14:24,895] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 07:14:24,896] {taskinstance.py:1250} INFO - Starting attempt 9 of 10
[2022-04-25 07:14:24,897] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 07:14:24,935] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): format_xl_to_pq_task> on 1997-01-01 00:00:00+00:00
[2022-04-25 07:14:24,947] {standard_task_runner.py:52} INFO - Started process 1991 to run task
[2022-04-25 07:14:24,955] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_pq_task', 'scheduled__1997-01-01T00:00:00+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpz3_4gsh4', '--error-file', '/tmp/tmpjdsd7sid']
[2022-04-25 07:14:24,958] {standard_task_runner.py:80} INFO - Job 328: Subtask format_xl_to_pq_task
[2022-04-25 07:14:25,321] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_pq_task scheduled__1997-01-01T00:00:00+00:00 [running]> on host 64c7187bd08f
[2022-04-25 07:14:25,540] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 07:14:25,709] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_pq_task
AIRFLOW_CTX_EXECUTION_DATE=1997-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1997-01-01T00:00:00+00:00
[2022-04-25 07:14:31,061] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_to_gcs_dag.py", line 57, in format_xl_to_pq
    pq.write_table(df, src_file.replace('.xlsx', '.parquet'))
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 2018, in write_table
    where, table.schema,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'schema'
[2022-04-25 07:14:31,188] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_pq_task, execution_date=19970101T000000, start_date=20220425T071424, end_date=20220425T071431
[2022-04-25 07:14:31,249] {standard_task_runner.py:98} ERROR - Failed to execute job 328 for task format_xl_to_pq_task ('DataFrame' object has no attribute 'schema'; 1991)
[2022-04-25 07:14:31,291] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 07:14:31,546] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
