[2022-05-02 17:02:50,231] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_dag.bq_create_partitioned_table_task manual__2022-05-02T16:54:02.970723+00:00 [queued]>
[2022-05-02 17:02:50,279] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_dag.bq_create_partitioned_table_task manual__2022-05-02T16:54:02.970723+00:00 [queued]>
[2022-05-02 17:02:50,281] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 17:02:50,283] {taskinstance.py:1239} INFO - Starting attempt 3 of 4
[2022-05-02 17:02:50,285] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 17:02:50,335] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_partitioned_table_task> on 2022-05-02 16:54:02.970723+00:00
[2022-05-02 17:02:50,347] {standard_task_runner.py:52} INFO - Started process 11351 to run task
[2022-05-02 17:02:50,355] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bq_dag', 'bq_create_partitioned_table_task', 'manual__2022-05-02T16:54:02.970723+00:00', '--job-id', '1356', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_task.py', '--cfg-path', '/tmp/tmpdh2r7liu', '--error-file', '/tmp/tmpb1q44iyf']
[2022-05-02 17:02:50,358] {standard_task_runner.py:77} INFO - Job 1356: Subtask bq_create_partitioned_table_task
[2022-05-02 17:02:50,743] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_to_bq_dag.bq_create_partitioned_table_task manual__2022-05-02T16:54:02.970723+00:00 [running]> on host 9f5021834e17
[2022-05-02 17:02:51,131] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_to_bq_dag
AIRFLOW_CTX_TASK_ID=bq_create_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-05-02T16:54:02.970723+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-02T16:54:02.970723+00:00
[2022-05-02 17:02:51,136] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-05-02 17:02:51,171] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 17:02:51,246] {bigquery.py:1637} INFO - Inserting job ***_gcs_to_bq_dag_bq_create_partitioned_table_task_2022_05_02T16_54_02_970723_00_00_28de6b551bce5e2357048c457969e7d1
[2022-05-02 17:02:52,912] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.InternalServerError: 500 An internal error occurred and the request could not be completed. This is usually caused by a transient issue. Retrying the job with back-off as described in the BigQuery SLA should solve the problem: https://cloud.google.com/bigquery/sla. If the error continues to occur please contact support at https://cloud.google.com/support. Error: 80038528

(job ID: airflow_gcs_to_bq_dag_bq_create_partitioned_table_task_2022_05_02T16_54_02_970723_00_00_28de6b551bce5e2357048c457969e7d1)

                                                                       -----Query Job SQL Follows-----                                                                       

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE intense-glow-347320.us_employment_all.us_employment_partitioned         AS         SELECT * FROM us_employment_all.us_employment_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-05-02 17:02:53,035] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_to_bq_dag, task_id=bq_create_partitioned_table_task, execution_date=20220502T165402, start_date=20220502T170250, end_date=20220502T170253
[2022-05-02 17:02:53,080] {standard_task_runner.py:92} ERROR - Failed to execute job 1356 for task bq_create_partitioned_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.InternalServerError: 500 An internal error occurred and the request could not be completed. This is usually caused by a transient issue. Retrying the job with back-off as described in the BigQuery SLA should solve the problem: https://cloud.google.com/bigquery/sla. If the error continues to occur please contact support at https://cloud.google.com/support. Error: 80038528

(job ID: airflow_gcs_to_bq_dag_bq_create_partitioned_table_task_2022_05_02T16_54_02_970723_00_00_28de6b551bce5e2357048c457969e7d1)

                                                                       -----Query Job SQL Follows-----                                                                       

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE intense-glow-347320.us_employment_all.us_employment_partitioned         AS         SELECT * FROM us_employment_all.us_employment_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-05-02 17:02:53,135] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-02 17:02:53,380] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
