[2022-04-25 07:27:10,234] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-25 07:27:10,284] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-25 07:27:10,286] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 07:27:10,289] {taskinstance.py:1250} INFO - Starting attempt 3 of 4
[2022-04-25 07:27:10,290] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 07:27:10,335] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): rm_files_task> on 1997-01-01 00:00:00+00:00
[2022-04-25 07:27:10,346] {standard_task_runner.py:52} INFO - Started process 3138 to run task
[2022-04-25 07:27:10,353] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'rm_files_task', 'scheduled__1997-01-01T00:00:00+00:00', '--job-id', '337', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp9cxbpfy7', '--error-file', '/tmp/tmp8kvuay4s']
[2022-04-25 07:27:10,356] {standard_task_runner.py:80} INFO - Job 337: Subtask rm_files_task
[2022-04-25 07:27:10,715] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [running]> on host 64c7187bd08f
[2022-04-25 07:27:11,025] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 07:27:11,219] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=rm_files_task
AIRFLOW_CTX_EXECUTION_DATE=1997-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1997-01-01T00:00:00+00:00
[2022-04-25 07:27:11,224] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-25 07:27:11,226] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm /opt/***//laucnty97.xlsx /opt/***/us_employment_97.parquet']
[2022-04-25 07:27:11,244] {subprocess.py:85} INFO - Output:
[2022-04-25 07:27:11,339] {subprocess.py:89} INFO - rm: cannot remove '/opt/***/us_employment_97.parquet': No such file or directory
[2022-04-25 07:27:11,343] {subprocess.py:93} INFO - Command exited with return code 1
[2022-04-25 07:27:11,467] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-04-25 07:27:11,504] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcp_dag, task_id=rm_files_task, execution_date=19970101T000000, start_date=20220425T072710, end_date=20220425T072711
[2022-04-25 07:27:11,558] {standard_task_runner.py:98} ERROR - Failed to execute job 337 for task rm_files_task (Bash command failed. The command returned a non-zero exit code 1.; 3138)
[2022-04-25 07:27:11,575] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 07:27:11,814] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
